package com.desafioitau.api.transferencia.v1.conta.exception;

public class ContaNotFoundException extends ContaException {
    public ContaNotFoundException(Throwable cause) {
        super(cause);
    }
}
