package com.desafioitau.api.transferencia.exceptions.cliente.exception;

public class ClienteNotFoundException extends ClienteException {
    public ClienteNotFoundException(Throwable cause) {
        super(cause);
    }
}
