package com.desafioitau.api.transferencia.exceptions.cliente.exception;

public class ClienteInternalServerErrorException extends ClienteException {
    public ClienteInternalServerErrorException(Throwable cause) {
        super(cause);
    }
}
