package com.desafioitau.api.transferencia.v1.notificacao.exception;

public class NotificacaoInternalServerErrorException extends NotificacaoException {
    public NotificacaoInternalServerErrorException(Throwable cause) {
        super(cause);
    }
}
